version: "3.8"
services:
  postgres:
    image: postgres:13.6
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ".data/postgresql:/var/lib/postgresql/data"
